### ISSUE TITLE
Cannot execute rake tasks

### ISSUE THREAD

**Issue by benjaminmateev** [nu7hatch/desantapp#1]
Hey,

I cloned the project and ran bundle. After that when I wanna run rake tasks I always get

```
rake aborted!
cannot load such file -- reusable/active_record_tasks
```

I added reusable explicitly to the Gemfile and ran bundler again but without luck, no matter whether I do bundle exec rake -T or foreman run rake -T it still throws the same error.

Edit: Same error with executing rake in the vagrant box after download, setup and ssh-ing in it.

Any help?

Thanks
Ben

**Comment by nu7hatch** [comment]
The `reusable` isn't a gem here, only a `lib/reusable` collection of common stuff. I guess you're getting this error cuz lib is not in your load path. I just pushed bugfix to the master, you can update your copy and try now, `rake -T` should work fine. Btw. remember to use `foreman run rake ...` for taks which requires environment to be loaded.

**Comment by benjaminmateev** [comment]
Thx man, but still the same problem. With or without vagrant, with or without foreman still the problem raised in lib/tasks/db.rake

**Comment by nu7hatch** [comment]
can u add:

```
puts $LOAD_PATH.inspect
```

to top of the Rakefile and post the result?

**Comment by benjaminmateev** [comment]
sure

```
["/Users/benjamenmateev/Sites/benmat/lib", "/Users/benjamenmateev/Sites/benmat/desantapp/Rakefile", "/Users/benjamenmateev/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib", "/Users/benjamenmateev/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1", "/Users/benjamenmateev/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/x86_64-darwin11.4.0", "/Users/benjamenmateev/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby", "/Users/benjamenmateev/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/vendor_ruby/1.9.1", "/Users/benjamenmateev/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/vendor_ruby/1.9.1/x86_64-darwin11.4.0", "/Users/benjamenmateev/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/vendor_ruby", "/Users/benjamenmateev/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1", "/Users/benjamenmateev/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/x86_64-darwin11.4.0"]
rake aborted!
cannot load such file -- reusable/active_record_tasks

(See full trace by running task with --trace)
```

this is the output. if I change

```
$LOAD_PATH.unshift(File.expand_path('../lib'), __FILE__)
```

to

```
$LOAD_PATH.unshift(File.expand_path('./lib'), __FILE__)
```

then this error disappears but the following one arrises:

```
rake aborted!
cannot load such file -- rspec/core/rake_task
```

**Comment by nu7hatch** [comment]
oh, wait in which directory you executing rake?

**Comment by nu7hatch** [comment]
aaargh, my mistake, i called put `__FILE__` outside of expand path call. just pushed bugfix, update your clone, should be fine now.

**Comment by benjaminmateev** [comment]
in desantapp, the directory that contains the Rakefile, the Gemfile, etc.

## 

Benjamin Mateev
CEO

http://www.urbanvention.com (http://www.urbanvention.com/)

Mobile: +49 176 32 13 92 68

---

The information contained in this message may be privileged and confidential and protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer. Thank you

**Comment by benjaminmateev** [comment]
Awesome, that solved it! Thanks a lot!!!
